# Generated by Django 5.2.4 on 2025-07-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_usuario_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='modificado',
            field=models.BooleanField(default=False),
        ),
    ]
